# use travis defaults from capybara-webkit
sudo: required
dist: trusty

addons:
  apt:
    sources:
    - ubuntu-sdk-team
    packages:
    - libqt5webkit5-dev
    - qtdeclarative5-dev

language: ruby
rvm:
  - 2.3
#  - 2.4 # not till rails 4.2.8 is released
cache: bundler
bundler_args: --path ../../vendor/bundle --without debug
gemfile:
  - spec/gemfiles/rails_4_2.gemfile
  - spec/gemfiles/rails_5_0.gemfile
  - spec/gemfiles/rails_5_1.gemfile

env:
  global:
    - QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
  matrix:
    # Username and password from http://docs.travis-ci.com/user/database-setup/
    - DB=sqlite3 DBC_VERBOSE=true
    #  - DB=mysql2     DB_USERNAME=root     DB_PASSWORD=""
    - DB=postgresql DB_USERNAME=postgres DB_PASSWORD=""

matrix:
  fast_finish: true
  allow_failures:
    - env: DB=sqlite3 DBC_VERBOSE=true

before_script:
  - RAILS_ENV=test bundle exec rake db:create db:migrate

script:
  - xvfb-run bundle exec rspec
  - bundle show rubocop
  - bundle exec rubocop
