# use travis defaults from capybara-webkit
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - ubuntu-sdk-team
    packages:
      - libqt5webkit5-dev
      - qtdeclarative5-dev

language: ruby
rvm:
  - 2.3.1

bundler_args: --path ../../vendor/bundle --without debug
gemfile:
  - spec/gemfiles/rails_4_2.gemfile
  - spec/gemfiles/rails_5_0.gemfile

env:
  global:
    - QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
  matrix:
  # Username and password from http://docs.travis-ci.com/user/database-setup/
  - DB=sqlite3
#  - DB=mysql2     DB_USERNAME=root     DB_PASSWORD=""
  - DB=postgresql DB_USERNAME=postgres DB_PASSWORD=""

#before_install:
#  - ls -al /usr/lib
#  - ls -al /usr/lib/x86_64-linux-gnu/
#  - ls -al /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
#  - gem install bundler -v 1.12.3

before_script:
  - RAILS_ENV=test bundle exec rake db:create db:migrate

script:
  - xvfb-run bundle exec rspec
  - bundle exec rubocop
