# use travis defaults from capybara-webkit
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - ubuntu-sdk-team
    packages:
      - libqt5webkit5-dev
      - qtdeclarative5-dev

language: ruby
rvm:
  - 2.3.1
  - 2.4
cache: bundler
bundler_args: --path ../../vendor/bundle --without debug
gemfile:
  - spec/gemfiles/rails_4_2.gemfile
  - spec/gemfiles/rails_5_0.gemfile

env:
  global:
    - QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
  matrix:
  # Username and password from http://docs.travis-ci.com/user/database-setup/
  - DB=sqlite3 SQLITE=file
#  - DB=mysql2     DB_USERNAME=root     DB_PASSWORD=""
#  - DB=postgresql DB_USERNAME=postgres DB_PASSWORD="" DBCLEANER=deletion
  - DB=postgresql DB_USERNAME=postgres DB_PASSWORD=""

before_script:
  - RAILS_ENV=test bundle exec rake db:create db:migrate

script:
  - xvfb-run bundle exec rspec
  - bundle exec rubocop
