<%
db_adapter = ENV.fetch('DB', 'sqlite3')
db_host    = ENV.fetch('DB_HOST', ENV.fetch('THREDDED_DB_1_PORT_5432_TCP_ADDR', 'localhost'))
db_port    = ENV['DB_PORT'] || ENV['THREDDED_DB_1_PORT_5432_TCP_ADDR'] ||
  {'postgresql' => 5432, 'mysql2' => 3306}[db_adapter]
sqlite_source = ENV.fetch('SQLITE', ENV['TRAVIS'] ? 'file' : 'memory')
require 'etc'
pool_size =
  # Web: max workers * max threads
  ENV.fetch('WEB_CONCURRENCY', 3).to_i * ENV.fetch('MAX_THREADS', 5).to_i +
  # ActiveJob Async max thread pool size
  Etc.nprocessors
puts "pool_size: #{pool_size}"
%>

defaults: &defaults
  host: <%= db_host %>
  port: <%= db_port %>
  adapter: <%= db_adapter %>
  encoding: utf8
  min_messages: WARNING
  pool: <%= pool_size %>
  username: <%= ENV.fetch('DB_USERNAME', 'thredded').inspect %>
  password: <%= ENV.fetch('DB_PASSWORD', 'thredded').inspect %>

development:
  <<: *defaults
  database: <%= db_adapter == 'sqlite3' ? 'db/development.sqlite3' : 'thredded_gem_dev' %>

test:
  <<: *defaults
  pool_size: 1
  <% if db_adapter == 'sqlite3'
       case sqlite_source
       when 'file' %>
  database: 'db/test.sqlite3'
  <%   when 'memory' %>
  database: ':memory:'
  <%   else
         fail "unexepcted sqlite_source '#{sqlite_source}'"
       end %>
  <% else %>
  database: 'thredded_gem_test'
  <% end %>

production:
  <<: *defaults
  encoding: utf8
  min_messages: WARNING
  url: <%= ENV['DATABASE_URL'].inspect if ENV['DATABASE_URL'] %>
  database: <%= (db_adapter == 'sqlite3' ? 'db/production.sqlite3' : 'thredded_gem_production') unless ENV['DATABASE_URL'] %>
